### ISSUE TITLE
Knowing when you've reached the last slide

### ISSUE THREAD

**Issue by egr103** [lukesnowden/FSVS#15]
Your plugin is probably the most reliable vertical slider plugins I've found. I know you said that your having trouble with mobile but on iPhone's it works great.

This is more of a question than an issue but I'm trying to go back to normal scrolling when you've reached the last slide. I have 4 slides using your plugin and as soon as you try to scroll further down the page I'd like to slide down to a normal scrolling area, akin to: http://www.hugeinc.com/ 

Is this even achievable with your plugin, if so could you point me in the direction of where in your code I should look to try and get this implemented?

**Comment by lukesnowden** [comment]
Hi @egr103, no, with FSVS1 you can't go back to "normal" scrolling. This version fully hijacks the scrolling for a single instance of the plugin to run. The site you mention does not hijack the scroll event. I have however started FSVS2 (http://luke.sno.wden.co.uk/full-screen-vertical-scroll/v2) which does implement what you describe but is far from finished and doesn't work on mobile.  The only way you can have scrolling is by having an area within a slide with a class of ```scrollable``` on. Regards.

**Comment by egr103** [comment]
Thanks for getting back to me. Thats a shame its not apart of this plugin but I understand. Back to drawing board for me then! Great plugin though :)
