### ISSUE TITLE
Firefox: Absolute Position Elements Stack on 1st Slide

### ISSUE THREAD

**Issue by joncursi** [lukesnowden/FSVS#16]
Firefox bug:

If you absolute position an element with CSS, regardless of what slide it is in, it will get thrown into the 1st slide and only display there. And I'm not sure how to fix this.

Here's a screenshot. I have images positioned absolute across 5 different slides. But in Firefox, they all get displayed in the first:
![screen shot 2015-03-21 at 12 38 12 am](https://cloud.githubusercontent.com/assets/4974609/6763777/bc3be3de-cf62-11e4-8aea-5c66cc990b90.png)

**Comment by lukesnowden** [comment]
Contain your slide with a div which is positioned relatively

**Comment by joncursi** [comment]
@lukesnowden that did it! Thanks!

**Comment by lukesnowden** [comment]
no worries!

--  
Luke Snowden
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by lukesnowden** [comment]
send me a link when its done, would like to see that working, looks good

**Comment by joncursi** [comment]
@lukesnowden will do, hopefully launching this beast in the beginning of April.

**Comment by joncursi** [comment]
@lukesnowden https://cryptuitive.com/ - thanks again for the awesome library! enjoy!

**Comment by lukesnowden** [comment]
nice! - add a showcase section to the readme file - https://github.com/lukesnowden/FSVS

**Comment by joncursi** [comment]
:+1:
