### ISSUE TITLE
Slide Up/Down Event?

### ISSUE THREAD

**Issue by bradleybell** [lukesnowden/FSVS#17]
Hi,

Is it possible to know the direction the user is sliding? i.e. If they go up an event happens and vice versa for down.

Or alternatively, is there a way of custom pagination? I basically want to use text headlines to achieve something similar to this: 
http://jsfiddle.net/peterhay/xrqjaxk7/

Thanks

**Comment by lukesnowden** [comment]
Im not sure what you after but this will determine direction: https://jsfiddle.net/bx90Ljuw/

**Comment by bradleybell** [comment]
Thats perfect, thanks so much!

**Comment by lukesnowden** [comment]
No worries, it's what I'm here for!

**Comment by bradleybell** [comment]
Sorry one last question.. On the custom pagination, is there any way of adding an 'active' class?
Thank you!

**Comment by lukesnowden** [comment]
Sorry for asking but do u know much is/query? Take a look at the exact function in the fsvs.js. If you can't figure it let me know and I'll sort a demo out for you

**Comment by lukesnowden** [comment]
(Not at my Mac at the minute)

**Comment by bradleybell** [comment]
My js knowledge is quite bad.. I'm looking at the exact function in bundle.js so I'll try and work it out!
Thanks again.

**Comment by lukesnowden** [comment]
I'll post u something late when I'm in

**Comment by bradleybell** [comment]
Got it! - https://jsfiddle.net/4Lqx76au/2/

Thank you :)

**Comment by lukesnowden** [comment]
boom! no worries

**Comment by bradleybell** [comment]
Hi Again, sorry to come back at you but I think I celebrated too early!
Basically I have the classes working when the pagination is clicked, but not added each time we scroll down as I get this reference error - [Error] ReferenceError: Can't find variable: currentSlideIndex
	(anonymous function) (show, line 54)

Which makes sense.. I just can't think of a solution round it. Any thoughts?
https://jsfiddle.net/4Lqx76au/6/

Thanks again

**Comment by bradleybell** [comment]
Got it!
https://jsfiddle.net/4Lqx76au/7/

Added variable and inserted the active class on callback.
