### ISSUE TITLE
Bullets label

### ISSUE THREAD

**Issue by tiago258** [lukesnowden/FSVS#23]
Is there a way to have a label for bullets on hover?

**Comment by lukesnowden** [comment]
You going to have to be a little more specific than that mate. Where?

**Comment by tiago258** [comment]
I want something like this: https://www.dropbox.com/s/f4vvswa74fnasa7/Captura%20de%20tela%202015-08-11%2016.11.30.png?dl=0. 
When put cursor above the bullets i want a label like in example.

**Comment by lukesnowden** [comment]
heres something to get you started: https://jsfiddle.net/4Lqx76au/8/

**Comment by tiago258** [comment]
Thanks very much :) It will help me :)
