### ISSUE TITLE
Cannot click on image links on mobile

### ISSUE THREAD

**Issue by pathetix** [lukesnowden/FSVS#24]
If I have a image wrapped in a link, the link becomes unclickable.

Eg:
```
        <p>
            <a href="http://www.google.com">
                <img src="image.jpg">
            </a>
        </p>
```

**Comment by lukesnowden** [comment]
what device? fiddle link? The only mouseclick events are here: https://github.com/lukesnowden/FSVS/blob/master/js/fsvs.js#L175 which there is no cancelation of the event.

**Comment by pathetix** [comment]
https://jsfiddle.net/pathetix/4geo5L55/1/

Basically any browser on mobile.
I forked your fiddle and added a normal link and one image link.
On my side the image link is not clickable.

**Comment by lukesnowden** [comment]
the links work fine for me..

**Comment by pathetix** [comment]
Oh that's strange. It didn't work for me on mobile.
Maybe this screencast helps?
https://db.tt/zjCB0tb3

**Comment by lukesnowden** [comment]
^ see above :+1:

**Comment by 0kai** [comment]
I had found the same issue, all my mobile phone can't click the image button. did you have any idea to this?

**Comment by 0kai** [comment]
@pathetix @lukesnowden 
I had modify some codes to fixed this issue. 
Maybe it's not a good idea, just for your information.

https://github.com/lukesnowden/FSVS/pulls
