### ISSUE TITLE
Firefox issues

### ISSUE THREAD

**Issue by AurelDragut** [lukesnowden/FSVS#38]
Hey,

I have some issues running the slider in Firefox:

- the mouse scroll is acting in reverse (if i scrool up i get the next slide instead of previous)
- i place content in the 4th slide and it appears in the first slide.

What can i do to fix that?

**Comment by AurelDragut** [comment]
fixed the scrolling issue by removing the - from e.detail in

var wheely = ( e.wheelDelta || e.detail || e.originalEvent.detail );

from the isScrollingUp function.

**Comment by lukesnowden** [comment]
drop us a pull request matey and ill pull it in.

**Comment by AurelDragut** [comment]
Done, any idea what to do with that content displayed in the opposite slide (first instead of the last)?

**Comment by lukesnowden** [comment]
cant see the pull request so cant pull it down to see what you are referring to. http://recordit.co/

**Comment by AurelDragut** [comment]
I guess i have done something wrong. now i got this:
![screen shot 2016-09-05 at 22 48 03](https://cloud.githubusercontent.com/assets/7759267/18256223/0c9f3b70-73bb-11e6-8137-351ec5e6bb02.png)

**Comment by lukesnowden** [comment]
no matter ill bosh it in and see whats happening
