### ISSUE TITLE
How can i set a function to run on a slide when getting on that slide?

### ISSUE THREAD

**Issue by AurelDragut** [lukesnowden/FSVS#40]
Hi, 

is there any way i can set the code so that when i get to a slide to run the content from that slide? for example i have a video on slide 3 that i want to start playing automatically when i get to slide3 and to stop when get out of the slide3...

**Comment by lukesnowden** [comment]
https://github.com/lukesnowden/FSVS/blob/master/assets/js/bundle.js#L397

```javascript
$.fn.fsvs({
    afterSlide : function( index ) {

   }
});
```
