### ISSUE TITLE
add a counter to slider

### ISSUE THREAD

**Issue by lucbord** [lukesnowden/FSVS#43]
Hi Luke,
great work! I have tried to add a counter to slider with:

          var totalItems = $('.slide').length;

            var currentIndex = $('.slide').index() + 1;
                $('.num').html(''+currentIndex+'/'+totalItems+'');

            $('#fsvs-body').bind('slid', function() {
                currentIndex = $('.active-slide').index() + 1;
                $('.num').html(''+currentIndex+'/'+totalItems+'');
            });

but when jump from a slide to another the number is not updated..  Any idea or suggestion?  
Thanks in advance!

**Comment by lukesnowden** [comment]
not sure what you are trying to achieve but just a heads up, you have a typo on this line;

```
$('#fsvs-body').bind('slid', function() {
```

**Comment by lukesnowden** [comment]
you can also do the following;

```
$.fn.fsvs({
    afterSlide: function( slideIndex ) {
        alert( slideIndex );
    }
});
