### ISSUE TITLE
Unable to select form fields on mobile with touch events enabled

### ISSUE THREAD

**Issue by scmacintosh** [lukesnowden/FSVS#8]
Hey, really love this script. 

With touch events enabled on a mobile device (tested on iOS and Android via Chrome debugger), form fields and DOM event listeners (including the fsvs pagination elements) become unresponsive to interaction. If I turn off touch events, everything works as intended.

**Comment by marco3211** [comment]
Yeah, I'm running into the same issue. Any fixes to that problem?

**Comment by lukesnowden** [comment]
I'll try and take a look later today

**Comment by lukesnowden** [comment]
try these amends, not had time to test it but think this should work

**Comment by marco3211** [comment]
Sure I'll give it a shot. Will let you know if anything comes up. Thanks!

**Comment by marco3211** [comment]
Yup other touch events respond well now, but the fsvs pagination is unresponsive. It's the other way around now. I'll try to help out as well when I got time.
