### ISSUE TITLE
_fsvs.scss using a undefined mixin (border-radius)

### ISSUE THREAD

**Issue by mrshannonyoung** [lukesnowden/FSVS#9]
`@include border-radius( 100% );`

Is not defined anywhere and errors out the compiler.

**Comment by lukesnowden** [comment]
You must be using an older version mate, uses gulp now

**Comment by mrshannonyoung** [comment]
This was pulled using Bower

http://bower.io/search/?q=full-screen-vertical-scroll

"full-screen-vertical-scroll":"latest"

**Comment by lukesnowden** [comment]
I am looking into this as we never were able to register the package on bowers repository as there is "something" wrong with the URL format that doesn't comply, so if it is on there, I did not add it.

**Comment by lukesnowden** [comment]
right try updating your bower package (may need changing to version 1.1.0) see if that helps any
